apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: guestbook-ui
  name: guestbook-ui
spec:
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - name: proxy
        image: hlesey/proxy:1.0
        envFrom:
        - configMapRef:
            name: guestbook-ui
        ports:
        - name: http-alt
          containerPort: 8080
        resources:
          requests:
            cpu: "20m"
            memory: "10Mi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guestbook-ui
data:
  PORT: '8080'
  REWRITE_MESSAGE: '{;{"admin_portal":true,'
  REDIRECT_URL: 'http://phippy-api'
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  selector:
    app: guestbook-ui
  ports:
  - name: http
    port: 80
    targetPort: http-alt
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook-ui
spec:
  rules:
  - host: guestbook-ui.local
    http:
      paths:
      - path: /
        backend:
          serviceName: guestbook-ui
          servicePort: 80